Bump Go to 1.19 and update Gardener dep
gardener/remedy-controller pull request #50
Opened 2023-01-24 10:26 UTC by elchead

**How to categorize this PR?**

/area TODO
/kind TODO
/platform azure

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2023-01-24 11:56 UTC, elchead commented
/review @kon-angelo

2023-01-25 12:13 UTC, kon-angelo commented on cmd/remedy-controller-azure/main.go
> +
Can you please format these imports ?

2023-01-25 12:21 UTC, kon-angelo requested changes

2023-01-25 12:21 UTC, kon-angelo commented on go.mod
>  replace (
I think you can remove most of these replace directives that reference old k8s version packages with the exception of client-go (at least this was the case with the other extensions until recently)

2023-01-27 08:37 UTC, closed without merging